// Generated by scripts/gen-starters.mjs — official preconstructed decklists
// (Proving Grounds + Origins Champion decks). Do not edit by hand.
import type { Deck } from './decks'

export const STARTER_DECKS: Deck[] = [
  {
    "id": "starter-annie",
    "name": "Starter — Annie (Fury/Chaos)",
    "legendId": "ogs-017-024",
    "championId": "ogs-010-024",
    "battlefieldIds": [
      "ogn-296-298",
      "ogn-296-298",
      "ogn-296-298"
    ],
    "runes": {
      "ogn-007-298": 6,
      "ogn-166-298": 6
    },
    "main": {
      "ogn-169-298": 3,
      "ogn-170-298": 3,
      "ogn-171-298": 3,
      "ogn-185-298": 3,
      "ogs-003-024": 3,
      "ogn-013-298": 2,
      "ogs-011-024": 2,
      "ogn-176-298": 3,
      "ogn-005-298": 3,
      "ogs-010-024": 2,
      "ogn-191-298": 3,
      "ogs-001-024": 2,
      "ogn-174-298": 3,
      "ogs-002-024": 3,
      "ogs-018-024": 2
    }
  },
  {
    "id": "starter-lux",
    "name": "Starter — Lux (Mind/Order)",
    "legendId": "ogs-021-024",
    "championId": "ogs-014-024",
    "battlefieldIds": [
      "ogn-288-298",
      "ogn-288-298",
      "ogn-288-298"
    ],
    "runes": {
      "ogn-089-298": 6,
      "ogn-214-298": 6
    },
    "main": {
      "ogn-095-298": 3,
      "ogn-103-298": 3,
      "ogn-210-298": 3,
      "ogn-084-298": 2,
      "ogn-087-298": 3,
      "ogn-206-298": 3,
      "ogs-014-024": 2,
      "ogn-219-298": 3,
      "ogn-085-298": 3,
      "ogs-006-024": 2,
      "ogs-016-024": 3,
      "ogn-105-298": 3,
      "ogs-012-024": 3,
      "ogn-088-298": 2,
      "ogs-022-024": 2
    }
  },
  {
    "id": "starter-garen",
    "name": "Starter — Garen (Body/Order)",
    "legendId": "ogs-023-024",
    "championId": "ogs-007-024",
    "battlefieldIds": [
      "ogn-294-298",
      "ogn-294-298",
      "ogn-294-298"
    ],
    "runes": {
      "ogn-126-298": 6,
      "ogn-214-298": 6
    },
    "main": {
      "ogn-210-298": 3,
      "ogn-129-298": 3,
      "ogn-130-298": 3,
      "ogn-132-298": 3,
      "ogn-211-298": 3,
      "ogn-222-298": 3,
      "ogn-206-298": 3,
      "ogn-219-298": 3,
      "ogn-131-298": 2,
      "ogn-215-298": 2,
      "ogs-024-024": 2,
      "ogs-007-024": 2,
      "ogs-013-024": 2,
      "ogs-016-024": 3,
      "ogs-015-024": 3
    }
  },
  {
    "id": "starter-yi",
    "name": "Starter — Master Yi (Calm/Body)",
    "legendId": "ogs-019-024",
    "championId": "ogs-004-024",
    "battlefieldIds": [
      "ogn-279-298",
      "ogn-279-298",
      "ogn-279-298"
    ],
    "runes": {
      "ogn-042-298": 6,
      "ogn-126-298": 6
    },
    "main": {
      "ogn-046-298": 3,
      "ogn-048-298": 3,
      "ogn-052-298": 3,
      "ogn-127-298": 3,
      "ogn-134-298": 3,
      "ogn-129-298": 2,
      "ogn-055-298": 3,
      "ogs-020-024": 2,
      "ogn-049-298": 3,
      "ogs-004-024": 2,
      "ogs-005-024": 3,
      "ogs-008-024": 3,
      "ogn-137-298": 3,
      "ogs-009-024": 2,
      "ogn-142-298": 2
    }
  },
  {
    "id": "starter-jinx",
    "name": "Champion Deck — Jinx (Fury/Chaos)",
    "legendId": "ogn-251-298",
    "championId": "ogn-030-298",
    "battlefieldIds": [
      "ogn-289-298",
      "ogn-298-298",
      "ogn-285-298"
    ],
    "runes": {
      "ogn-007-298": 6,
      "ogn-166-298": 6
    },
    "main": {
      "ogn-169-298": 3,
      "ogn-168-298": 3,
      "ogn-008-298": 2,
      "ogn-003-298": 3,
      "ogn-185-298": 3,
      "ogn-182-298": 3,
      "ogn-036-298": 1,
      "ogn-030-298": 1,
      "ogn-006-298": 3,
      "ogn-165-298": 2,
      "ogn-024-298": 2,
      "ogn-180-298": 2,
      "ogn-019-298": 3,
      "ogn-001-298": 2,
      "ogn-178-298": 2,
      "ogn-002-298": 3,
      "ogn-011-298": 1,
      "ogn-195-298": 1
    }
  },
  {
    "id": "starter-leesin",
    "name": "Champion Deck — Lee Sin (Calm/Body)",
    "legendId": "ogn-257-298",
    "championId": "ogn-151-298",
    "battlefieldIds": [
      "ogn-282-298",
      "ogn-289-298",
      "ogn-280-298"
    ],
    "runes": {
      "ogn-042-298": 6,
      "ogn-126-298": 6
    },
    "main": {
      "ogn-043-298": 2,
      "ogn-052-298": 3,
      "ogn-136-298": 3,
      "ogn-128-298": 3,
      "ogn-058-298": 3,
      "ogn-060-298": 1,
      "ogn-055-298": 3,
      "ogn-132-298": 3,
      "ogn-053-298": 2,
      "ogn-135-298": 2,
      "ogn-152-298": 1,
      "ogn-147-298": 3,
      "ogn-065-298": 3,
      "ogn-151-298": 1,
      "ogn-125-298": 2,
      "ogn-157-298": 1,
      "ogn-137-298": 2,
      "ogn-142-298": 2
    }
  },
  {
    "id": "starter-viktor",
    "name": "Champion Deck — Viktor (Mind/Order)",
    "legendId": "ogn-265-298",
    "championId": "ogn-246-298",
    "battlefieldIds": [
      "ogn-294-298",
      "ogn-293-298",
      "ogn-275-298"
    ],
    "runes": {
      "ogn-089-298": 6,
      "ogn-214-298": 6
    },
    "main": {
      "ogn-090-298": 2,
      "ogn-095-298": 2,
      "ogn-209-298": 3,
      "ogn-213-298": 2,
      "ogn-093-298": 2,
      "ogn-216-298": 3,
      "ogn-101-298": 2,
      "ogn-103-298": 3,
      "ogn-206-298": 2,
      "ogn-094-298": 2,
      "ogn-084-298": 3,
      "ogn-222-298": 3,
      "ogn-111-298": 1,
      "ogn-083-298": 2,
      "ogn-208-298": 3,
      "ogn-246-298": 1,
      "ogn-086-298": 2,
      "ogn-118-298": 1,
      "ogn-233-298": 1
    }
  },
  {
    "id": "custom-leesin-massimo",
    "name": "Mon deck — Lee Sin (collection)",
    "legendId": "ogn-257-298",
    "championId": "ogn-151-298",
    "battlefieldIds": [
      "ogn-282-298",
      "ogn-289-298",
      "ogn-283-298"
    ],
    "runes": {
      "ogn-042-298": 6,
      "ogn-126-298": 6
    },
    "main": {
      "ogn-151-298": 1,
      "ogn-052-298": 3,
      "ogn-136-298": 3,
      "ogn-139-298": 2,
      "ogn-054-298": 3,
      "ogn-132-298": 3,
      "ogn-055-298": 2,
      "ogn-150-298": 1,
      "ogn-061-298": 2,
      "ogn-141-298": 1,
      "ogn-065-298": 1,
      "ogn-049-298": 1,
      "ogn-157-298": 1,
      "ogn-046-298": 3,
      "ogn-128-298": 2,
      "ogn-129-298": 2,
      "ogn-127-298": 2,
      "ogn-050-298": 2,
      "ogn-058-298": 1,
      "ogn-154-298": 1,
      "ogn-043-298": 1,
      "ogn-152-298": 1,
      "ogn-063-298": 1
    }
  }
]
